### ISSUE TITLE
403 Forbidden for maven

### ISSUE THREAD

**Issue by milapchokshi-simformsolutions** [bytedance/tiktok-business-android-sdk#18]
As per your document i added below maven into project
maven { url 'https://dl.bintray.com/aweme-open-sdk-team/public' }

after adding maven url  getting error 403 forbidden error for this url (https://dl.bintray.com/aweme-open-sdk-team/public)
![image](https://user-images.githubusercontent.com/63447084/128167212-c1554cda-e965-4ef2-9f65-9f907dc68bf5.png)

Due to that project can not build successfully.

**Comment by akhiljames** [comment]
Hi @milapchokshi-simformsolutions since JCenter & Bintray shut down, please use jitpack: https://jitpack.io/#bytedance/tiktok-business-android-sdk
