### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [bytedance/tiktok-business-android-sdk#2]
https://github.com/bytedance/tiktok-business-android-sdk/blob/e490c4cecb66012cf42af9cd3acb4921247b9518/business-core/src/main/java/com/tiktok/appevents/TTCrashHandler.java#L21

This field is never used.

**Comment by sakopqiu** [comment]
Thx, will do

**Comment by sakopqiu** [comment]
BOT
